### ISSUE TITLE
"Security Policy Handling Failed" if "All Logins" notification selected

### ISSUE THREAD

**Issue by SkinnyBill** [steadramon/cpanel_addon-twostepauth#7]
If a user sets their email notification setting to "All Logins", when they attempt to authenticate, they are presented with the following error:

Security Policy Handling Failed
Please contact the system admin or check the error_log file.

In order to recover account access, the reseller/root must log in to WHM options for 2SA and "disable" for the user. Then the user can log in again and change their email preference from "All Logins", and re-enable 2SA.

The last 30 lines of /usr/local/cpanel/logs/error_log are below, with some personal information removed. If i removed something relevant or didn't include enough lines, let me know.

	securitypolicy: Called because of TwoStepAuth failing check.
	securitypolicy: Called because of TwoStepAuth failing check.
	securitypolicy: Called because of TwoStepAuth failing check.
	securitypolicy: Called because of TwoStepAuth failing check.
	securitypolicy: Called because of TwoStepAuth failing check.
	securitypolicy: Called because of TwoStepAuth failing check.
	[2015-02-18 00:32:53 +0000] warn [Cpanel::SafeDir::MK] mkdir /var/cpanel/user_notifications/*cpanel_username*/history failed: Permission denied at /usr/local/cpanel/Cpanel/SafeDir/MK.pm line 174
		Cpanel::SafeDir::MK::safemkdir('/var/cpanel/user_notifications/*cpanel_username*/history', 493) called at /usr/local/cpanel/Cpanel/MultiUserDirStore.pm line 69
		Cpanel::MultiUserDirStore::new('Cpanel::iContact::History', 'user', '*cpanel_username*', 'keep_time', 864000, 'subdir', 'history', 'dir', '/var/cpanel/user_notifications') called at /usr/local/cpanel/Cpanel/MultiUserDirStore/TimeIndexedData.pm line 48
		Cpanel::MultiUserDirStore::TimeIndexedData::new('Cpanel::iContact::History', 'keep_time', 864000, 'dir', '/var/cpanel/user_notifications', 'subdir', 'history', 'user', '*cpanel_username*') called at /usr/local/cpanel/Cpanel/iContact/History.pm line 43
		Cpanel::iContact::History::new('Cpanel::iContact::History', 'user', '*cpanel_username*') called at /usr/local/cpanel/Cpanel/iContact.pm line 757
		Cpanel::iContact::_save_notification_to_log('log_user', '*cpanel_username*', 'app', 'Notice', 'email_args_hr', HASH(*removed*)) called at /usr/local/cpanel/Cpanel/iContact.pm line 336
		Cpanel::iContact::icontact('user', '*cpanel_username*', 'application', 'Notice', 'subject', '[login] Login to account *cpanel_username* on *cpanel_hostname*.', 'message', 'We are sending you this email further to your successful login to the control panel on *cpanel_hostname*.\x0A\x0AUsername: *cpanel_username*\x0AIP Address: *0.0.0.0*\x0ABrowser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.3.18 (KHTML, like Gecko) Version/8.0.3 Safari/600.3.18\x0ATime: Wed, 18 Feb 2015 00:32:53 GMT\x0A\x0A\x0A', 'msgtype', '', 'to', '*cpanel_username*') called at /usr/local/cpanel/Cpanel/Security/Policy/TwoStepAuth/UI/HTML.pm line 122
		Cpanel::Security::Policy::TwoStepAuth::UI::HTML::process(Cpanel::Security::Policy::TwoStepAuth::UI::HTML=HASH(*removed*), HASH(*removed*), HASH(*removed*), HASH(*removed*)) called at /usr/local/cpanel/Cpanel/SecurityPolicy.pm line 120
		Cpanel::SecurityPolicy::process_violated_policy(Cpanel::Security::Policy::TwoStepAuth=HASH(*removed*), HASH(*removed*), HASH(*removed*), HASH(*removed*)) called at base/securitypolicy.cgi.pl line 133
		eval {...} called at base/securitypolicy.cgi.pl line 121
	Security Policy requires exec termination.
	The system failed to create the directory “/var/cpanel/user_notifications/*cpanel_username*/history” because of an error: Permission denied
	 at /usr/local/cpanel/Cpanel/Exception.pm line 127.
		Cpanel::Exception::new("Cpanel::Exception::IO::DirectoryCreateError", HASH(*removed*)) called at /usr/local/cpanel/Cpanel/Exception.pm line 57
		Cpanel::Exception::create("IO::DirectoryCreateError", HASH(*removed*)) called at /usr/local/cpanel/Cpanel/MultiUserDirStore.pm line 69
		Cpanel::MultiUserDirStore::new("Cpanel::iContact::History", "user", "*cpanel_username*", "keep_time", 864000, "subdir", "history", "dir", "/var/cpanel/user_notifications", ...) called at /usr/local/cpanel/Cpanel/MultiUserDirStore/TimeIndexedData.pm line 48
		Cpanel::MultiUserDirStore::TimeIndexedData::new("Cpanel::iContact::History", "keep_time", 864000, "dir", "/var/cpanel/user_notifications", "subdir", "history", "user", "*cpanel_username*", ...) called at /usr/local/cpanel/Cpanel/iContact/History.pm line 43
		Cpanel::iContact::History::new("Cpanel::iContact::History", "user", "*cpanel_username*") called at /usr/local/cpanel/Cpanel/iContact.pm line 757
		Cpanel::iContact::_save_notification_to_log("log_user", "*cpanel_username*", "app", "Notice", "email_args_hr", HASH(*removed*)) called at /usr/local/cpanel/Cpanel/iContact.pm line 336
		Cpanel::iContact::icontact("user", "*cpanel_username*", "application", "Notice", "subject", "[login] Login to account *cpanel_username* on *cpanel_hostname*.", "message", "We are sending you this email further to your successful logi"..., "msgtype", ...) called at /usr/local/cpanel/Cpanel/Security/Policy/TwoStepAuth/UI/HTML.pm line 122
		Cpanel::Security::Policy::TwoStepAuth::UI::HTML::process(Cpanel::Security::Policy::TwoStepAuth::UI::HTML=HASH(*removed*), HASH(*removed*), HASH(*removed*), HASH(*removed*)) called at /usr/local/cpanel/Cpanel/SecurityPolicy.pm line 120
		Cpanel::SecurityPolicy::process_violated_policy(Cpanel::Security::Policy::TwoStepAuth=HASH(*removed*), HASH(*removed*), HASH(*removed*), HASH(*removed*)) called at base/securitypolicy.cgi.pl line 133
		eval {...} called at base/securitypolicy.cgi.pl line 121
	 at base/securitypolicy.cgi.pl line 141.

**Comment by steadramon** [comment]
Hmm, that's using cPanel internal iContact stuff - I'll have to have a look into it, could you confirm the perms on /var/cpanel/user_notifications/ and /var/cpanel/user_notifications/<username> for me? (ls -lahd /path/to/dir)

**Comment by SkinnyBill** [comment]
```drwxr-xr-x 5 root root 4.0K Feb 11 23:56 /var/cpanel/user_notifications/```

I assume you meant to write two different directories, but you wrote /var/cpanel/user_notifications/ twice :)

**Comment by steadramon** [comment]
apologies, github scrubbed my formatting - also /var/cpanel/user_notifications/username

**Comment by SkinnyBill** [comment]
```drwxr-x--- 3 root *username* 4.0K Feb 11 23:54 /var/cpanel/user_notifications/*username*```
I think i may see the issue here :)

**Comment by steadramon** [comment]
Hmm what version of cPanel are you running? As I'm using all internal cPanel calls here I'm not sure if there's anything I can do really.

I see some bugs around iContact have been fixed in the latest 11.48 - https://documentation.cpanel.net/display/ALD/11.48+Change+Log

**Comment by SkinnyBill** [comment]
Sorry for the delay. I just checked and I am running 11.48 build 13, and I'm still getting this issue.
It's worth noting that i'm running the release branch, not the stable branch.

**Comment by dhawton** [comment]
I'm having this issue as well, same error messages and permissions.  Version 11.48.2 Build 3.
